### PR TITLE
Fix #100: Use maven toolchains if configured

### LINKED ISSUE #100: maven Toolchains not used to set the java version
First of all, thanks for your work and for this great plugin.

We have multiple JDK versions installed and managed with toolchains plugin in our builds.
Unfortunately, the vertx-maven-plugin doesn't give the possibility of configuring which JDK to use.

Is there any way to do this or can you point me of helping implementing it?

Thanks in advance

### PR DESCRIPTION
**Pull request by mgazanayi**

### CODE REVIEW

**Comment by mgazanayi** [comment]
@cescoffier : The `JavaProcessExecutor` is only a part of the problem.

I got this also : 

```
Caused by: java.lang.UnsupportedClassVersionError: com/vidal/fhirstore/Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1 (Native Method)
    at java.lang.ClassLoader.defineClass (ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass (SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass (URLClassLoader.java:468)
    at java.net.URLClassLoader.access$100 (URLClassLoader.java:74)
    at java.net.URLClassLoader$1.run (URLClassLoader.java:369)
    at java.net.URLClassLoader$1.run (URLClassLoader.java:363)
    at java.security.AccessController.doPrivileged (Native Method)
    at java.net.URLClassLoader.findClass (URLClassLoader.java:362)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:357)
    at io.reactiverse.vertx.maven.plugin.mojos.AbstractRunMojo.isVertxLauncher (AbstractRunMojo.java:354)
    at io.reactiverse.vertx.maven.plugin.mojos.AbstractRunMojo.execute (AbstractRunMojo.java:151)
    at io.reactiverse.vertx.maven.plugin.mojos.RunMojo.execute (RunMojo.java:73)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by mgazanayi** [comment]
The thing is that it's always not taking in account the version of Java that the verticle is compiled with, so it crashes when loaded. Any ideas of what I should look for ?

**Comment by cescoffier** [comment]
there is in the plugin a default configuration for the Maven Compiler Plugin. It may require some tuning to avoid the issue.

**Comment by tsegismont** [comment]
The plugin has been refactored to manage both Vert.x 4 and Vert.x 5 in #593

It may be simpler to use maven toolchains now

**Pull request closed without merging**
