### PR TITLE
resolve the space error in the classpath.

### PR DESCRIPTION
**Pull request by abel533**
Error Before: 

```
[DEBUG] Executing command :cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_151\jre\bin\java.exe" -cp ;F:\Git\git-clone-share\target\classes;d:\.m2\rep
ository\io\vertx\vertx-core\3.5.3\vertx-core-3.5.3.jar;d:\.m2\repository\io\vertx\vertx-rx-java\3.5.3\vertx-rx-java-3.5.3.jar;d:\.m2\repository\io\ver
tx\vertx-web\3.5.3\vertx-web-3.5.3.jar;d:\.m2\repository\io\vertx\vertx-web-templ-freemarker\3.5.3\vertx-web-templ-freemarker-3.5.3.jar;d:\.m2\reposit
ory\io\vertx\vertx-jdbc-client\3.5.3\vertx-jdbc-client-3.5.3.jar;d:\.m2\repository\org\hsqldb\hsqldb\2.3.4\hsqldb-2.3.4.jar;d:\.m2\repository\ch\qos\l
ogback\logback-classic\1.2.3\logback-classic-1.2.3.jar;d:\.m2\repository\io\vertx\vertx-core\3.5.3\vertx-core-3.5.3.jar;d:\.m2\repository\io\netty\net
ty-common\4.1.19.Final\netty-common-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-buffer\4.1.19.Final\netty-buffer-4.1.19.Final.jar;d:\.m2\reposit
ory\io\netty\netty-transport\4.1.19.Final\netty-transport-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-handler\4.1.19.Final\netty-handler-4.1.19.
Final.jar;d:\.m2\repository\io\netty\netty-codec\4.1.19.Final\netty-codec-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-handler-proxy\4.1.19.Final
\netty-handler-proxy-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-codec-socks\4.1.19.Final\netty-codec-socks-4.1.19.Final.jar;d:\.m2\repository\i
o\netty\netty-codec-http\4.1.19.Final\netty-codec-http-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-codec-http2\4.1.19.Final\netty-codec-http2-4.
1.19.Final.jar;d:\.m2\repository\io\netty\netty-resolver\4.1.19.Final\netty-resolver-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-resolver-dns\4.
1.19.Final\netty-resolver-dns-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-codec-dns\4.1.19.Final\netty-codec-dns-4.1.19.Final.jar;d:\.m2\reposit
ory\com\fasterxml\jackson\core\jackson-core\2.9.5\jackson-core-2.9.5.jar;d:\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.9.5\jackson-d
atabind-2.9.5.jar;d:\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.9.5\jackson-annotations-2.9.5.jar;d:\.m2\repository\io\vertx\vert
x-rx-java\3.5.3\vertx-rx-java-3.5.3.jar;d:\.m2\repository\io\reactivex\rxjava\1.3.5\rxjava-1.3.5.jar;d:\.m2\repository\io\vertx\vertx-web\3.5.3\vertx-
web-3.5.3.jar;d:\.m2\repository\io\vertx\vertx-auth-common\3.5.3\vertx-auth-common-3.5.3.jar;d:\.m2\repository\io\vertx\vertx-bridge-common\3.5.3\vert
x-bridge-common-3.5.3.jar;d:\.m2\repository\io\vertx\vertx-web-templ-freemarker\3.5.3\vertx-web-templ-freemarker-3.5.3.jar;d:\.m2\repository\org\freem
arker\freemarker\2.3.23\freemarker-2.3.23.jar;d:\.m2\repository\io\vertx\vertx-jdbc-client\3.5.3\vertx-jdbc-client-3.5.3.jar;d:\.m2\repository\io\vert
x\vertx-sql-common\3.5.3\vertx-sql-common-3.5.3.jar;d:\.m2\repository\com\mchange\c3p0\0.9.5.2\c3p0-0.9.5.2.jar;d:\.m2\repository\com\mchange\mchange-
commons-java\0.2.11\mchange-commons-java-0.2.11.jar;d:\.m2\repository\org\hsqldb\hsqldb\2.3.4\hsqldb-2.3.4.jar;d:\.m2\repository\ch\qos\logback\logbac
k-classic\1.2.3\logback-classic-1.2.3.jar;d:\.m2\repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;d:\.m2\repository\org\slf4j\slf4j
-api\1.7.25\slf4j-api-1.7.25.jar;D:\Program Files (x86)\apache-maven-3.5.0\bin\..\boot\plexus-classworlds-2.5.2.jar io.vertx.core.Launcher run com.gi
thub.abel533.git.GitHttpVerticle --redeploy=F:\Git\git-clone-share\target\classes/**/* --redeploy-scan-period=1000 redeploy-termination-period=1000 --
launcher-class="io.vertx.core.Launcher""
```

error path:

```
D:\Program Files (x86)\apache-maven-3.5.0\bin\..\boot\plexus-classworlds-2.5.2.jar
```

solution: add double quotes.

Correct command:

```shell
[DEBUG] Executing command :cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_151\jre\bin\java.exe" -cp ";F:\Git\git-clone-share\target\classes;d:\.m2\rep
ository\io\vertx\vertx-core\3.5.3\vertx-core-3.5.3.jar;d:\.m2\repository\io\vertx\vertx-rx-java\3.5.3\vertx-rx-java-3.5.3.jar;d:\.m2\repository\io\ver
tx\vertx-web\3.5.3\vertx-web-3.5.3.jar;d:\.m2\repository\io\vertx\vertx-web-templ-freemarker\3.5.3\vertx-web-templ-freemarker-3.5.3.jar;d:\.m2\reposit
ory\io\vertx\vertx-jdbc-client\3.5.3\vertx-jdbc-client-3.5.3.jar;d:\.m2\repository\org\hsqldb\hsqldb\2.3.4\hsqldb-2.3.4.jar;d:\.m2\repository\ch\qos\l
ogback\logback-classic\1.2.3\logback-classic-1.2.3.jar;d:\.m2\repository\io\vertx\vertx-core\3.5.3\vertx-core-3.5.3.jar;d:\.m2\repository\io\netty\net
ty-common\4.1.19.Final\netty-common-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-buffer\4.1.19.Final\netty-buffer-4.1.19.Final.jar;d:\.m2\reposit
ory\io\netty\netty-transport\4.1.19.Final\netty-transport-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-handler\4.1.19.Final\netty-handler-4.1.19.
Final.jar;d:\.m2\repository\io\netty\netty-codec\4.1.19.Final\netty-codec-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-handler-proxy\4.1.19.Final
\netty-handler-proxy-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-codec-socks\4.1.19.Final\netty-codec-socks-4.1.19.Final.jar;d:\.m2\repository\i
o\netty\netty-codec-http\4.1.19.Final\netty-codec-http-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-codec-http2\4.1.19.Final\netty-codec-http2-4.
1.19.Final.jar;d:\.m2\repository\io\netty\netty-resolver\4.1.19.Final\netty-resolver-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-resolver-dns\4.
1.19.Final\netty-resolver-dns-4.1.19.Final.jar;d:\.m2\repository\io\netty\netty-codec-dns\4.1.19.Final\netty-codec-dns-4.1.19.Final.jar;d:\.m2\reposit
ory\com\fasterxml\jackson\core\jackson-core\2.9.5\jackson-core-2.9.5.jar;d:\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.9.5\jackson-d
atabind-2.9.5.jar;d:\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.9.5\jackson-annotations-2.9.5.jar;d:\.m2\repository\io\vertx\vert
x-rx-java\3.5.3\vertx-rx-java-3.5.3.jar;d:\.m2\repository\io\reactivex\rxjava\1.3.5\rxjava-1.3.5.jar;d:\.m2\repository\io\vertx\vertx-web\3.5.3\vertx-
web-3.5.3.jar;d:\.m2\repository\io\vertx\vertx-auth-common\3.5.3\vertx-auth-common-3.5.3.jar;d:\.m2\repository\io\vertx\vertx-bridge-common\3.5.3\vert
x-bridge-common-3.5.3.jar;d:\.m2\repository\io\vertx\vertx-web-templ-freemarker\3.5.3\vertx-web-templ-freemarker-3.5.3.jar;d:\.m2\repository\org\freem
arker\freemarker\2.3.23\freemarker-2.3.23.jar;d:\.m2\repository\io\vertx\vertx-jdbc-client\3.5.3\vertx-jdbc-client-3.5.3.jar;d:\.m2\repository\io\vert
x\vertx-sql-common\3.5.3\vertx-sql-common-3.5.3.jar;d:\.m2\repository\com\mchange\c3p0\0.9.5.2\c3p0-0.9.5.2.jar;d:\.m2\repository\com\mchange\mchange-
commons-java\0.2.11\mchange-commons-java-0.2.11.jar;d:\.m2\repository\org\hsqldb\hsqldb\2.3.4\hsqldb-2.3.4.jar;d:\.m2\repository\ch\qos\logback\logbac
k-classic\1.2.3\logback-classic-1.2.3.jar;d:\.m2\repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;d:\.m2\repository\org\slf4j\slf4j
-api\1.7.25\slf4j-api-1.7.25.jar;D:\Program Files (x86)\apache-maven-3.5.0\bin\..\boot\plexus-classworlds-2.5.2.jar" io.vertx.core.Launcher run com.gi
thub.abel533.git.GitHttpVerticle --redeploy=F:\Git\git-clone-share\target\classes/**/* --redeploy-scan-period=1000 redeploy-termination-period=1000 --
launcher-class="io.vertx.core.Launcher""
```

### CODE REVIEW

**Comment by cescoffier** [comment]
Shouldn't these changes be made only on windows?

**Comment by abel533** [comment]
This problem occurs when there are spaces, regardless of the operating system.

**Comment by cescoffier** [comment]
Great, so we can easily reproduce it in an integration-test. I will have a look.

**Comment by cescoffier** [comment]
@abel533 I'm trying to reproduce it without luck so far. All my ITs pass even when using spaces in the directory names. Did you try on linux or mac?

**Comment by abel533** [comment]
Try it on the windows system.
Put maven in the `Program Files (x86)` directory.

**Comment by tsegismont** [comment]
Closing this one, I'll reopen another PR with tests for Windows

**Pull request closed without merging**
